smp.c <- read.csv2("C:/Users/brico/Documents/13_Mathématiques/Statistiques/MOOC/DATA/smp1.csv")
str(smp.c)
barplot(table(smp.c$prof))
pie(table(smp.c$prof))
hist(table(smp.c$age), col="grey",main="", xlab="age")
boxplot(smp.c$age, xlab="age")
boxplot(smp.c$age~smp.c$rs, ylab="age", xlab="Recherche des sensation")
plot(smp.c$age, smp.c$n.enfant)
plot(jitter(smp.c$age), jitter(smp.c$n.enfant))
repdat <- read.csv2("C:/Users/brico/Documents/13_Mathématiques/Statistiques/MOOC/DATA/outils_hdrs.csv")
str(repdat)
library(gplots)
plotmeans(repdat$HDRS~repdat$VISIT,gap=0,barcol="black")
interaction.plot(repdat$VISIT,repdat$NUMERO,repdat$HDRS,lty=1,legend=FALSE)

summary(smp.c)
library(prettyR)
describe(smp.c)
describe(smp.c, num.desc=c("mean","sd","median","min","max","valid.n"))
mean(smp.c$age, na.rm=TRUE)
sd(smp.c$age, na.rm=TRUE)
table(smp.c$prof, deparse.level=2, useNA="always")
